#!/bin/sh
PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

# copy tpm unseal binary
copy_exec /usr/bin/tpm_unsealdata

# copy tpm-sealed keys
for key in /.private/*.tpm ; do
	copy_file zfs-tpm "$key" "/$(basename "$key")"
done
