#!/bin/sh
PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

# stop tcsd so that systemd can start & control it
if pidof tcsd >/dev/null ; then
	kill $(pidof tcsd)
fi
