#!/bin/sh
PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

# tcsd requires ip communication
if ! ip link show lo | grep -q UP ; then
	ip link set lo up
fi

# start tcsd
/sbin/tcsd
